//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatedQR.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int EventID { get; set; }
        public string UserCode { get; set; }
        public string FullName { get; set; }
        public string CCCD { get; set; }
        public string Phone { get; set; }
        public string Facility { get; set; }
        public string Office { get; set; }
        public string Email { get; set; }
        public int isCheck { get; set; }
        public string Description { get; set; }
        public string UserCreated { get; set; }
        public string UserUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual Events Events { get; set; }
    }
}
